version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${PG_PW}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_DB: "${PG_DB}"
    ports:
      - "${PG_PORT}:5432"
    networks  :
      - postgres
    volumes:
      - postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PG_ADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PG_ADMIN_PW}"
    ports:
      - "${PG_ADMIN_PORT}:80" 
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
